buttons:
  turn_on: "ğŸŸ¢  Turn on"
  turn_off: "ğŸ”´  Turn off"
  adjust_posting_interval: "ğŸ“†ï¸  Adjust posting interval"
  adjust_random_interval: "ğŸ²  Adjust random interval"
  adjust_rejected_content_lifespan: "ğŸ—‘ï¸â³  Adjust rejected content lifespan"
  adjust_posted_content_lifespan: "ğŸ“œâ³ï¸  Adjust posted content lifespan"
  accept: "ğŸ‘  Accept"
  reject: "ğŸ‘  Reject"
  go_back: "â¬…ï¸  Go back"
  undo: "â†©ï¸  Undo"
  edit: "âœï¸ Edit"
  edit_caption: "âœï¸ Edit caption"
  edit_hashtags: "âœï¸ Edit hashtags"
  remove_from_view: "âŒ  Remove"
  remove_from_queue: "âŒ  Remove from queue"

labels:
  settings_title: "âš™ï¸  Settings  ğŸ”§\n\nğŸ•’"
  accepted_caption: "âœ…  Accepted"
  rejected_caption: "ğŸ‘  Rejected"
  posted_caption: "ğŸ“¬  Posted"
  queued_caption: "â³  Queued"
  failed_caption: "âš ï¸  Failed"
  last_updated_caption: "ğŸ•’  Last updated"
